
MEMORY_SIZE = 10**6
BATCH_SIZE = 1024
ALPHA = 0.01
BETA = 0.02
TAU = 0.01
GAMMA = 0.95
UPDATE_EVERY = 100

THETA = 0.15
SIGMA = 0.3
DT = 1e-2
X0 = None


N_GAMES = 60001
FIGURE_FILE = 'MADDPG/plots/score.png'
FIGURE_FILE2 = 'MADDPG/plots/critic_actor_loss.png'
CHECKPOINT_DIR = 'MADDPG/tmp/maddpg'
LOAD_CHECKPOINT = False

WEIGHT_INIT = 'lecun_normal'
BIAS_INIT = 'lecun_normal'
CRITIC_DENSE1 = 128
CRITIC_DENSE2 = 128
#CRITIC_DENSE3 = 128
#CRITIC_DENSE4 = 64

ACTORS_DENSE1 = 128
ACTORS_DENSE2 = 128
#ACTORS_DENSE3 = 128
#ACTORS_DENSE4 = 64

CRITIC_ACTIVATION_HIDDEN = 'relu'
CRITIC_ACTIVATION_OUTPUT = None
ACTORS_ACTIVATION_HIDDEN = 'relu'
ACTORS_ACTIVATION_OUTPUT = None

CRITIC_LOSS = []
ACTORS_LOSS = []
UPDATE_EPISODES = []
SCORES_HISTORY = []
AVG_SCORE = 0