
MEMORY_SIZE = 10**6
BATCH_SIZE = 1024
ALPHA = 0.001
BETA = 0.002
TAU = 0.01
GAMMA = 0.95
NOISE = 0.1
UPDATE_EVERY = 100


N_GAMES = 20001
FIGURE_FILE = 'MADDPG/plots/score.png'
FIGURE_FILE2 = 'MADDPG/plots/critic_actor_loss.png'
CHECKPOINT_DIR = 'MADDPG/tmp/maddpg'
LOAD_CHECKPOINT = False

WEIGHT_INIT = 'lecun_normal'
BIAS_INIT = 'lecun_normal'
CRITIC_DENSE1 = 512
CRITIC_DENSE2 = 512

ACTORS_DENSE1 = 512
ACTORS_DENSE2 = 512

CRITIC_ACTIVATION_HIDDEN = 'relu'
CRITIC_ACTIVATION_OUTPUT = None
ACTORS_ACTIVATION_HIDDEN = 'relu'
ACTORS_ACTIVATION_OUTPUT = 'sigmoid'

CRITIC_LOSS = []
ACTORS_LOSS = []
UPDATE_EPISODES = []
SCORES_HISTORY = []
AVG_SCORE = 0